name: Automation to create tags

on: workflow_dispatch

jobs:
  update_tags:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      - name: Make the script files executable
        run: chmod +x scripts/scriptAutomatitionAzureGalatea.sh
      - name: generate Tags and copy Scripts of Automatition
        env: 
          VAR_NAME_REPOSITORY: ${{ github.repository }}
        run: scripts/scriptAutomatitionAzureGalatea.sh
        shell: bash
     
