name: Automation to create tags

on: workflow_dispatch

jobs:
  update_tags:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      - name: Make the script files executable
        run: chmod +x scripts/scriptAutomatitionAzureGalatea.sh
      - name: generate Tags and copy Scripts of Automatition
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAR_NAME_ROOT_REPOSITORY: "repo_de_prueba"
        run: scripts/scriptAutomatitionAzureGalatea.sh
        shell: bash
      - name: Push Changes
        run: |
          git config user.name bot-bancolombia-toolkit-innersource
          git config user.email oficina_open_source@bancolombia.com.co
          git add .
          git commit -m "chore: Upload Changes bot action bancolombia toolkit innersource"
          git push
        shell: bash
     
