name: Automation to create tags

on: workflow_dispatch

jobs:
  update_tags:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      - name: Make the script files executable
        run: chmod +x scripts/scriptAutomatitionAzureGalatea.sh
     # - name: generate Tags and copy Scripts of Automatition
     #   env: 
     #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #     VAR_NAME_ROOT_REPOSITORY: "repo_de_prueba"
     #   run: scripts/scriptAutomatitionAzureGalatea.sh
     #   shell: bash
      - name: generate custom labels
        env: 
          VAR_CUSTOM_LABELS : "GALATEA"
        run: |
          file_labels="./Toolkit/labels$VAR_CUSTOM_LABELS.csv"
          echo $file_labels
          ls ..
          cd repo_de_prueba/

          cat "$file_labels" | while IFS= read -r line;
          do
             if [[ $line != "" ]];
             then
              IFS_antiguo=$IFS
              IFS=";" 
              read -ra partes <<< "$line"
              IFS=$IFS_antiguo
              gh label create "${partes[0]}" --description "${partes[1]}" --color "${partes[2]}" -f
              echo "${partes[0]}"
             fi
          done

        shell: bash
     # - name: Push Changes
     #   run: |
     #     git config user.name yo
     #     git config user.email sebastianrodriguezvelasquez@gmail.com
     #     git add .
     #     git commit -m "chore: Upload Changes bot action bancolombia toolkit innersource"
     #     git push
     #   shell: bash
     
