name: Automation to create ISSUES on the support team's board in Azure

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    permissions: write-all
    if: contains(github.event.issue.labels.*.name, 'c:bug')
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Mostrar información del Issue Title
        run: pip install requests

      - name: Mostrar información del Issue Title
        run: pip3 install requests

      - name: Mostrar información del Issue Title
        run: echo "Nuevo Issue creado = ${{ github.event.issue.title }}"

      - name: Mostrar información del Issue Body
        run: echo "Nuevo Issue creado = ${{ github.event.issue.body }}"

      - name: Mostrar información del Issue ID
        run: echo "Nuevo Issue creado = ${{ github.event.issue.id }}"
      
      - name: Mostar Informacion del Issue URL
        run: echo "Nuevo Issue creado = ${{ github.event.issue.url }}"

      - name: Ejecutar script para crear ISSUE
        run: python scripts/create_issue_support.py
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{github.event.issue.url}}
          REPO_NAME: ${{github.repository}}
          GITHUB_SECRET: ${{secrets.GITHUB_TOKEN}}
